### ISSUE TITLE
Tablet Feed/Filter Concept

### ISSUE THREAD

**Issue by DigitalSismo** [stakes/fluid-framer#1]
Hi Jay,

Do you happen to have the framer project for your awesome "Tablet Feed/Filter Concept" available somewhere ?
It would make my day if you could share it.

Thank you very much.

**Comment by stakes** [comment]
I can dig it back up! I'll find it and clean it up a little, and then share the URL here. Thanks!

**Comment by DigitalSismo** [comment]
Thank you so much !
Best regards.

**Comment by DigitalSismo** [comment]
Hi James,

Did you get a chance to dig it back up ?

Thanks!

**Comment by yetimade** [comment]
Also having issues with this. Would the framer file be available?

**Comment by stakes** [comment]
Hey guys - I'll look into the issues described in #2 and see what's going on. Thanks!

**Comment by yetimade** [comment]
@stakes thanks!

**Comment by yetimade** [comment]
Any updates on this?
